config/routes.rb
Dnc::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations'}

  resources :members

  root to: 'info#intro'
  
  get 'about' => 'info#about', as: 'about'

  

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_attached_file :picture,
      storage: :dropbox,
      dropbox_credentials: Rails.root.join("config/dropbox.yml"),
      styles: { small: "400x380>" }

  has_attached_file :cover_photo,
      storage: :dropbox,
      dropbox_credentials: Rails.root.join("config/dropbox.yml"),
      styles: { big: "1920x1000>", small: "720x560>" }
      
  do_not_validate_attachment_file_type :cover_photo
  validates :description, presence: true, length: { maximum: 542}

  belongs_to :user
  
  def previous
    self.class.first(:conditions => ["id < ?", id], :order => "id desc")
  end

  def next
    self.class.first(:conditions => ["id > ?", id], :order => "id asc")
  end
  
  scope :with_user, where("`user_id` IS NOT NULL AND `user_id` !=''")

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_one :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def intro
    @intro_page = true
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.with_user
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @users = User.all 
    @member = Member.new(member_params)
    assing_user_to_member(@member, @users)
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render action: 'show', status: :created, location: @member }
      else
        format.html { render action: 'new' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :nickname, :last_name, :description, :picture, :cover_photo, :user_id)
    end
    
    def assing_user_to_member(member, users)
      if users.count != 0
        user = users.last 
        member.user_id = user.id if member.user_id == nil
        member.save
      end
    end
    
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_filter :require_no_authentication, only: [:cancel]
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to new_member_path(@user), notice: 'Please fill in more information.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
      
    end
  end

  private
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(name, path, css = "")
    css += if request.path.include?(path)
      " active" 
    else
       ""
    end
    content_tag :li, link_to(name, path), :class => css
  end

  def decide_css_class
    css_class = "team" if controller.class == MembersController || controller.class == Users::RegistrationsController || controller.class == Devise::SessionsController
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    flash_alerts = []
    error_key = 'errors.messages.not_saved'

    if !flash.empty?
      flash_alerts.push(flash[:error]) if flash[:error]
      flash_alerts.push(flash[:alert]) if flash[:alert]
      flash_alerts.push(flash[:notice]) if flash[:notice]
      error_key = 'devise.failure.invalid'
    end

    return "" if resource.errors.empty? && flash_alerts.empty?
    errors = resource.errors.empty? ? flash_alerts : resource.errors.full_messages

    messages = errors.map { |msg| content_tag(:p, msg) }.join
    sentence = I18n.t(error_key, :count    => errors.count,
                                 :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/members_helper.rb
module MembersHelper
  
  def editing_background_image(member)
    "background: url(" + member.cover_photo.url(:big) + ");" if member.present?
  end
end

app/views/info/_about_content.html.erb
<div class="row about">
  <div class="span12">
    <p>
      Zespół powstał we wrześniu 2012 roku z inicjatywy Michała Bochynka i Jacka Jackowskiego po rozpadzie ich poprzedniej grupy. Zamierzali stworzyć zespół czysto rockowy i na początku skupiali się na graniu kawałków takich kapel jak: Led&nbsp;Zeppelin, Deep Purple, czy Black Sabbath. W lutym 2013 roku nastapiło rozbudowanie składu kapeli o osobę Mateusza, który został gitarzystą prowadzącym. Jego dołączenie do składu zmotywowało nas do szybkiego działania i już w kwietniu wystąpiliśmy w pełnym składzie z Wilkiem i Adamem jako Dazed 'N' Confused. Od tamtej pory intensywnie pracujemy nad własnym materiałem. Równolegle staramy spotykać się z publicznością podczas koncertów. Mieliśmy okazję występować m.in we Wrocławiu oraz podczas wielu imprez na terenie Jeleniej Góry i okolic. Największym osiągnięciem zespołu jest zdobycie pierwszego miejsca w konkursie "Jelenia ma Talent 2".
    </p>
  </div>
</div>

app/views/info/about.html.erb
<%= render 'about_content' %>

app/views/info/intro.html.erb
<div class="row intro">
  <div class="span12 before_click">
    <%= image_tag('intro/big_logo_complete.png')%>
    <button type="button" class="button">Open</button>
  </div>
</div>
<span class="intro_page_partials">
  <%= render 'about_content' %>
</span>
<!-- <div class="after_click">
  <div class="span6 first_half">
    <%= image_tag('intro/big_logo_first_half.png',    :class => 'logo-image')%>
    <%= image_tag('intro/open_button_first_half.png', :class => 'button-image')%>
  </div>
  <div class="span6 second_half">
    <%= image_tag('intro/big_logo_second_half.png',    :class => 'logo-image')%>
    <%= image_tag('intro/open_button_second_half.png', :class => 'button-image')%>
  </div>

</div> -->

app/views/layouts/_nav.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav">
      <li><%= nav_link("About", about_path) %></li>
      <li><%= nav_link("Team", members_path)%></li>
      <% if user_signed_in? %>
        <li><%= nav_link("Add a new member", new_user_registration_path) %></li>
        <li><%= nav_link("My profile", member_path(current_user.member)) if current_user.member.present? %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= nav_link("Login", new_user_session_path) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dnc</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <div class="container <%= decide_css_class %>">
      <% if @intro_page %>
        <span class="intro_page_partials">
      <% end %>
      <%= yield %>    
    </div>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_for @member, html: { multipart: true } do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
    <% if @member.picture.present? %>
      <%= image_tag @member.picture.url(:small) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :cover_photo %>
    <%= f.file_field :cover_photo %>
  </div>
  
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit "Update", :class => "button" %>
  </div>
<% end %>

app/views/members/edit.html.erb
<div class="container team">
  <section class="story edit" data-speed="8" data-type="background" style="<%= editing_background_image(@member) %> 50% 0 no-repeat fixed; background-size: 100%;">
    <div class="form-container">
      <h1>Editing <%= @member.nickname %></h1>
      <%= render 'form' %>
      <p class="cancel-button">
        <%= link_to 'Cancel', members_path, class: "button cancel", data: { confirm: "Are you sure? All changes will be lost!" } %>  
      </p>
    </div>
  </section>
</div>

app/views/members/index.html.erb
<div class="loader">
  <span>Loading profiles, please wait</span>
</div>
<%= link_to 'New Member', new_member_path %>
<% @members.each do |member| %>
  <section class="story non-scroll" id="<%= member.id.to_words %>" data-speed="8" data-type="background" style="background: url(<%= member.cover_photo.url(:big) %>) 50% 0 no-repeat fixed; background-size: 120%;">
    <div data-type="sprite" data-offsetY="950" data-Xposition="25%" data-speed="2"></div>
    <article>
      <div class="container">
        <% if member.previous %>
          <a class="nav top" href="#<%= member.previous.id.to_words %>"><%= image_tag("arrow-top.png") %></a>
        <% end %>
        <div class="text">
          <p><%= member.description %></p>
          <% if member.user == current_user %>
            <span>
              <%= link_to 'Edit', edit_member_path(member), class: "button" %>
            </span>
          <% end %>
        </div>
        <div class="avatar"><%= image_tag member.picture.url(:small) %></div>
        <h1><%= member.nickname %></h1>
      <% if member.next %>  
        <a class="nav down" href="#<%= member.next.id.to_words %>"><%= image_tag("arrow-down.png") %></a>
      <% end %>
      </div>
    </article>
  </section>
<% end %>

app/views/members/new.html.erb
<div class="container team">
  <section class="story edit" data-speed="8" data-type="background" style="<%= editing_background_image(@member) %> 50% 0 no-repeat fixed; background-size: 100%;">
    <div class="form-container">
      <h1>Add a new member</h1>
      <%= render 'form' %>
      <p class="cancel-button">
        <%= link_to 'Cancel', members_path, class: "button cancel", data: { confirm: "Are you sure? All changes will be lost!" } %>  
      </p>
    </div>
  </section>
</div>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<section class="story" id="<%= @member.id.to_words %>" data-speed="8" data-type="background" style="background: url(<%= @member.cover_photo.url(:big) %>) 50% 0 no-repeat fixed; background-size: 120%;">
  <div data-type="sprite" data-offsetY="950" data-Xposition="25%" data-speed="2"></div>
  <article>
    <div class="container">
      <div class="text">
        <p><%= @member.description %></p>
        <span>
          <%= link_to 'Edit', edit_member_path(@member), class: "button" %>
          <%= link_to 'Back', members_path, class: "button" %>
        </span>
      </div>
      <div class="avatar"><%= image_tag @member.picture.url(:small) %></div>
      <h1><%= @member.nickname %></h1>
    </div>
  </article>
</section>